# Generated by Django 4.1.7 on 2023-02-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmDirectors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='information',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
