# Generated by Django 4.1.7 on 2023-02-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmDirectors', '0002_author_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(default='', upload_to='filmPosters'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(upload_to='directors'),
        ),
    ]
