# Generated by Django 4.1.7 on 2023-02-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmDirectors', '0004_alter_author_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='synopsis',
            field=models.TextField(max_length=500),
        ),
    ]
