# Generated by Django 4.1.7 on 2023-03-01 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmDirectors', '0005_alter_film_synopsis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='name',
            new_name='title',
        ),
    ]
