# Generated by Django 4.1.7 on 2023-03-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmDirectors', '0006_rename_name_film_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
